display_icon_titles:
  default: true
  description:
    en: "Display titles"

icons_size:
  default: 1.5
  description:
    en: "This setting changes the CSS font-size property of the icons (unit is em)"

tab_1_settings:
  default: "聊天, comment, /chat"
  description:
    en: "Format is: <code>&lt;title&gt;, &lt;FA5 icon&gt;, &lt;relative url or route name&gt;, &lt;enabled? default true (optional)&gt;</code>"

tab_2_settings:
  default: "个人, user, userActivity"

tab_3_settings:
  default: "主页, house, /"

tab_4_settings:
  default: "个性化, gear, preferences"

tab_5_settings:
  default: "私信, envelope, userPrivateMessages"

tab_6_settings:
  default: "收藏, bookmark, userActivity.bookmarks"

extend_fa5_icons:
  type: list
  default: ""
  description:
    en: "Use this setting to add any icons you want to use that are not included in the default FA5 icons subset"

match_url_params:
  default: false
  description:
    en: "Match full url without trim params"
